### ISSUE TITLE
make[all] failed to compile

### ISSUE THREAD

**Issue by kirk86** [facebook/fbthrift#184] opened 2016-10-16 15:14 UTC
Hi I've installed everything in terms of dependencies on my ubuntu 16.04 machine and when it comes to installing fbthrift it fails miserably.

```
 make[4]: *** No rule to make target 'generate/templates/py3/ServiceCallbacks.pxi.mustache', needed by 'all-am'.  Stop.
make[4]: *** Waiting for unfinished jobs....
make[4]: Leaving directory '/home/user/fblualib/fbthrift/thrift/compiler'
Makefile:926: recipe for target 'all-recursive' failed
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory '/home/user/fblualib/fbthrift/thrift/compiler'
Makefile:614: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/home/user/fblualib/fbthrift/thrift/compiler'
Makefile:499: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/user/fblualib/fbthrift/thrift'
Makefile:431: recipe for target 'all' failed
make: *** [all] Error 2
``` 

Any ideas on how to overcome this?

**Comment by lukenels** [comment] 2016-10-16 15:39
@buchuki Looks like in bb0004cdbe5b30c4f1a4fbd1fda223e8dd6e19f1 you forgot to remove `ServiceCallbacks.pxi.mustache` from the Makefile :)

**Comment by buchuki** [comment] 2016-10-16 17:14
I'll fix it tomorrow, thanks! 

⁣​

**Comment by kirk86** [comment] 2016-10-16 17:23
When I execute `autoreconf -if` I get the following warnings

```
lib/cpp2/Makefile.am:109: warning: variable 'thrift2include_fatal_SOURCES' is defined but no program or
lib/cpp2/Makefile.am:109: library has 'thrift2include_fatal' as canonical name (possible typo)
```
Following the suggestion of @lukenels I removed `ServiceCallbacks.pxi.mustache` from `Makefile`, `Makefile.am` and `Makefile.in` and now I'm getting the following errors

```
make[4]: Leaving directory '/home/user/fblualib/fbthrift/thrift/compiler'
Makefile:925: recipe for target 'all-recursive' failed
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory '/home/user/fblualib/fbthrift/thrift/compiler'
Makefile:613: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/home/user/fblualib/fbthrift/thrift/compiler'
Makefile:499: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/user/fblualib/fbthrift/thrift'
Makefile:431: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by jonaspku** [comment] 2016-10-18 06:14
i got the same problem. don't know what to do...

**Comment by juchem** [comment] 2016-10-18 06:43
what's the full output?
can you run `make --debug --trace` and provide the output of that as well?

**Comment by jonaspku** [comment] 2016-10-18 06:53
actrually, i notice that you fb team is testing this project...  right now...
and got the same problem...
PS: fb team test it in Ubuntu 14.04 
https://travis-ci.org/facebook/fbthrift

**Comment by kirk86** [comment] 2016-10-18 12:15
Hi @juchem, here is a log output from make. Hope that it helps. 
[logs.txt](https://github.com/facebook/fbthrift/files/536147/logs.txt)

**Comment by juchem** [comment] 2016-10-19 21:54
should be fixed by adb7441c8fa85b7e9ca4fe50157b60a6ad513587

**Closed by juchem** 2016-10-19 21:54 UTC

**Comment by kirk86** [comment] 2016-10-19 23:05
@juchem thanks a bunch! 👍 I am on Ubuntu 16.04 and everything works fine until the `make` step. I am able to compiler successfully but I get an error when I issue `sudo make install` or simple `make install`.

`sudo make install`

```
Making install in compiler
make[1]: Entering directory '/home/user/projects/torch/fblualib/fblualib/fbthrift/thrift/compiler'
make  install-recursive
make[2]: Entering directory '/home/user/projects/torch/fblualib/fblualib/fbthrift/thrift/compiler'
Making install in .
make[3]: Entering directory '/home/user/projects/torch/fblualib/fblualib/fbthrift/thrift/compiler'
make[4]: Entering directory '/home/user/projects/torch/fblualib/fblualib/fbthrift/thrift/compiler'
 /bin/mkdir -p '/usr/local/bin'
  /bin/bash ../libtool   --mode=install /usr/bin/install -c thrift1 '/usr/local/bin'
libtool: install: /usr/bin/install -c thrift1 /usr/local/bin/thrift1
 /bin/mkdir -p '/usr/local/share/thrift/templates/java/swift'
 /usr/bin/install -c -m 644 generate/templates/java/swift/BoxedType.mustache generate/templates/java/swift/Constants.mustache generate/templates/java/swift/ConstantValue.mustache generate/templates/java/swift/Enum.mustache generate/templates/java/swift/FieldType.mustache generate/templates/java/swift/Object.mustache generate/templates/java/swift/Requiredness.mustache generate/templates/java/swift/Service.mustache generate/templates/java/swift/Struct.mustache generate/templates/java/swift/Type.mustache generate/templates/java/swift/Union.mustache generate/templates/java/swift/ThriftFieldAnnotation.mustache generate/templates/java/swift/AutoGenerated.mustache '/usr/local/share/thrift/templates/java/swift'
 /bin/mkdir -p '/usr/local/share/thrift/templates/py3'
 /usr/bin/install -c -m 644 generate/templates/py3/OneStruct.pxd.mustache generate/templates/py3/Struct.pxd.mustache generate/templates/py3/CppFieldType.mustache generate/templates/py3/ServiceCallbacks.mustache generate/templates/py3/CythonFieldType.mustache generate/templates/py3/CythonServer.pyx.mustache generate/templates/py3/CythonStructGetter.mustache generate/templates/py3/OneServiceWrapper.h.mustache generate/templates/py3/CythonReturnValue.mustache generate/templates/py3/ServicesWrapper.pxd.mustache generate/templates/py3/CythonPromises.mustache generate/templates/py3/Services.pxd.mustache generate/templates/py3/ServicesWrapper.h.mustache generate/templates/py3/Struct.pxd.mustache generate/templates/py3/ServicesWrapper.cpp.mustache generate/templates/py3/OneServiceWrapper.cpp.mustache generate/templates/py3/CythonAssignField.mustache generate/templates/py3/CppPassField.mustache generate/templates/py3/CythonCppToPython.mustache generate/templates/py3/AutoGeneratedC.mustache generate/templates/py3/AutoGeneratedPy.mustache '/usr/local/share/thrift/templates/py3'
/usr/bin/install: will not overwrite just-created '/usr/local/share/thrift/templates/py3/Struct.pxd.mustache' with 'generate/templates/py3/Struct.pxd.mustache'
Makefile:901: recipe for target 'install-py3_DATA' failed
make[4]: *** [install-py3_DATA] Error 1
make[4]: Leaving directory '/home/user/projects/torch/fblualib/fblualib/fbthrift/thrift/compiler'
Makefile:1092: recipe for target 'install-am' failed
make[3]: *** [install-am] Error 2
make[3]: Leaving directory '/home/user/projects/torch/fblualib/fblualib/fbthrift/thrift/compiler'
Makefile:929: recipe for target 'install-recursive' failed
make[2]: *** [install-recursive] Error 1
make[2]: Leaving directory '/home/user/projects/torch/fblualib/fblualib/fbthrift/thrift/compiler'
Makefile:1086: recipe for target 'install' failed
make[1]: *** [install] Error 2
make[1]: Leaving directory '/home/user/projects/torch/fblualib/fblualib/fbthrift/thrift/compiler'
Makefile:498: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1

****  Installation failed. Aborting package creation.
``` 

`make install`

```
Making install in compiler
make[1]: Entering directory '/home/user/projects/torch/fblualib/fblualib/fbthrift/thrift/compiler'
make  install-recursive
make[2]: Entering directory '/home/user/projects/torch/fblualib/fblualib/fbthrift/thrift/compiler'
Making install in .
make[3]: Entering directory '/home/user/projects/torch/fblualib/fblualib/fbthrift/thrift/compiler'
make[4]: Entering directory '/home/user/projects/torch/fblualib/fblualib/fbthrift/thrift/compiler'
 /bin/mkdir -p '/usr/local/bin'
  /bin/bash ../libtool   --mode=install /usr/bin/install -c thrift1 '/usr/local/bin'
libtool: install: /usr/bin/install -c thrift1 /usr/local/bin/thrift1
/usr/bin/install: cannot remove '/usr/local/bin/thrift1': Permission denied
Makefile:684: recipe for target 'install-binPROGRAMS' failed
make[4]: *** [install-binPROGRAMS] Error 1
make[4]: Leaving directory '/home/user/projects/torch/fblualib/fblualib/fbthrift/thrift/compiler'
Makefile:1092: recipe for target 'install-am' failed
make[3]: *** [install-am] Error 2
make[3]: Leaving directory '/home/user/projects/torch/fblualib/fblualib/fbthrift/thrift/compiler'
Makefile:929: recipe for target 'install-recursive' failed
make[2]: *** [install-recursive] Error 1
make[2]: Leaving directory '/home/user/projects/torch/fblualib/fblualib/fbthrift/thrift/compiler'
Makefile:1086: recipe for target 'install' failed
make[1]: *** [install] Error 2
make[1]: Leaving directory '/home/user/projects/torch/fblualib/fblualib/fbthrift/thrift/compiler'
Makefile:498: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1

****  Installation failed. Aborting package creation.
```

Any ideas?

**Comment by juchem** [comment] 2016-10-20 00:09
I believe we have a fix in the oven for this. cc: @buchuki

**Comment by kirk86** [comment] 2016-10-20 02:10
@juchem awesome! Looking forward to it!

**Comment by buchuki** [comment] 2016-10-20 16:43
Yes, I'm really sorry for the delay on this. The fix went out for review on Tuesday, but I was travelling all day yesterday and only just landed it. It should be syncing to github soon.

**Comment by fengwhu** [comment] 2016-12-02 06:35
I got the same error when `sudo make install`.
```
/usr/bin/install: will not overwrite just-created ‘/usr/local/share/thrift/templates/py3/ConstantCythonFieldType.mustache’ with ‘generate/templates/py3/ConstantCythonFieldType.mustache’
make[4]: *** [install-py3_DATA] Error 1
make[4]: Leaving directory `/home/travis/build/facebook/fbthrift/thrift/compiler'
make[3]: *** [install-am] Error 2
make[3]: Leaving directory `/home/travis/build/facebook/fbthrift/thrift/compiler'
make[2]: *** [install-recursive] Error 1
make[2]: Leaving directory `/home/travis/build/facebook/fbthrift/thrift/compiler'
make[1]: *** [install] Error 2
make[1]: Leaving directory `/home/travis/build/facebook/fbthrift/thrift/compiler'
make: *** [install-recursive] Error 1
```
And I found that the build status of fbthrift project is still failing.
https://travis-ci.org/facebook/fbthrift

**Comment by buchuki** [comment] 2016-12-02 16:24
@fengwhu I've reproduced this, I'll get a fix out soon. In the meantime, you can delete this line https://github.com/facebook/fbthrift/blob/master/thrift/compiler/Makefile.am#L131 I accidentally included it twice -- apparently because I don't understand where `s` and `t` are in the alphabet.

**Comment by fengwhu** [comment] 2016-12-04 03:07
@buchuki THX, the `overwrite` problem has been solved.
But another error occurred. It seems a PYTHONPATH error just like your build output.
https://travis-ci.org/facebook/fbthrift
```
/home/yf/anaconda2/bin/python setup.py install --root= 
running install
Checking .pth file support in home/yf/anaconda2/lib/python2.7/site-packages/
/home/yf/anaconda2/bin/python -E -c pass
TEST FAILED: home/yf/anaconda2/lib/python2.7/site-packages/ does NOT support .pth files
error: bad install directory or PYTHONPATH

You are attempting to install a package to a directory that is not
on PYTHONPATH and which Python does not read ".pth" files from.  The
installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    home/yf/anaconda2/lib/python2.7/site-packages/

and your PYTHONPATH environment variable currently contains:

    ''
```
