### ISSUE TITLE
how to resolve such error during compile cpp2 lib? "ValueError: zero length field name in format"

### ISSUE THREAD

**Issue by jiangtaixu** [facebook/fbthrift#78] opened 2015-03-08 02:01 UTC
It report following error during compiling lib/cpp2, would anybody can give me some advice?

 File "/usr/lib64/python2.6/runpy.py", line 122, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.6/runpy.py", line 34, in _run_code
    exec code in run_globals
  File "/root/opensource/fbthrift/thrift/.python-local/lib/python/thrift_py-0.9.0-py2.6.egg/thrift_compiler/main.py", line 260, in <module>
    main()
  File "/root/opensource/fbthrift/thrift/.python-local/lib/python/thrift_py-0.9.0-py2.6.egg/thrift_compiler/main.py", line 257, in main
    conf.process(params)
  File "/root/opensource/fbthrift/thrift/.python-local/lib/python/thrift_py-0.9.0-py2.6.egg/thrift_compiler/main.py", line 240, in process
    frontend.process(params, generate_wrapper)
  File "/root/opensource/fbthrift/thrift/.python-local/lib/python/thrift_py-0.9.0-py2.6.egg/thrift_compiler/main.py", line 238, in generate_wrapper
    self.generate(*args)
  File "/root/opensource/fbthrift/thrift/.python-local/lib/python/thrift_py-0.9.0-py2.6.egg/thrift_compiler/main.py", line 234, in generate
    g.generate_program()
  File "/root/opensource/fbthrift/thrift/.python-local/lib/python/thrift_py-0.9.0-py2.6.egg/thrift_compiler/generate/t_generator.py", line 83, in generate_program
    self._generate(item)
  File "/root/opensource/fbthrift/thrift/.python-local/lib/python/thrift_py-0.9.0-py2.6.egg/thrift_compiler/generate/t_cpp_generator.py", line 3558, in _generate
    gen_func(self, what)
  File "/root/opensource/fbthrift/thrift/.python-local/lib/python/thrift_py-0.9.0-py2.6.egg/thrift_compiler/generate/t_cpp_generator.py", line 527, in _generate_service
    self._generate_processor(service, s)
  File "/root/opensource/fbthrift/thrift/.python-local/lib/python/thrift_py-0.9.0-py2.6.egg/thrift_compiler/generate/t_cpp_generator.py", line 1432, in _generate_processor
    out(), 'reqCtx')
  File "/root/opensource/fbthrift/thrift/.python-local/lib/python/thrift_py-0.9.0-py2.6.egg/thrift_compiler/generate/t_cpp_generator.py", line 1049, in _generate_app_ex
    out('ctx->userException({});'.format(uex_str))
ValueError: zero length field name in format

**Comment by facebook-github-bot-8** [comment] 2015-08-05 18:02
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by michaelhutt** [comment] 2015-09-15 19:26
For anyone else hitting this: if you're using Python 2.6 (or Python 3.1 apparently), the problem is that implicit argument numbering in string formatting is not supported. There are a few places in `thrift/compiler/py/generate/t_cpp_generator.py` that do this. Quick patch made: https://gist.github.com/michaelhutt/ac7a656c6f9987efa3a1

You'll have to do a `make clean` to get it to pick up the change, but it should allow you to continue.

**Comment by eduardo-elizondo** [comment] 2017-09-18 18:36
Closing to clean and provide better support to new issues. We are rewriting docs and guides on how to support this.

**Closed by eduardo-elizondo** 2017-09-18 18:36 UTC
